# Docs: https://datadoghq.atlassian.net/wiki/spaces/SECENG/pages/5138645099/User+guide+dd-octo-sts
issuer: https://token.actions.githubusercontent.com

subject: repo:DataDog/rustls-cng-crypto:pull_request

claim_pattern:
  event_name: pull_request
  head_ref: renovate/.*
  job_workflow_ref: DataDog/rustls-cng-crypto/\.github/workflows/renovate-sync-licenses\.yml@refs/pull/[0-9]+/merge

permissions:
  contents: write
